import { Avatar, FaceShape, HairStyle, NO_ITEM, findItem, lighten } from './avatar-model';

/**
 * Which parts of the character to draw, in which order, and in which colours.
 *
 * The drawing itself is not here. It lives in `src/assets/avatar/parts.svg`,
 * generated from `scripts/avatar-art/geometry.js`, where every hair style is
 * fitted to every face by construction. This file only NAMES parts from it
 * and says how to colour them — which is why detailed art costs the first
 * load nothing: the app ships these few names, not the paths.
 *
 * DOM-free, so the rules can be tested without rendering anything.
 */

/** Where the parts live. Relative, so it resolves against the app's own base. */
export const SPRITE = 'assets/avatar/parts.svg';

/**
 * Below this, fine detail turns to mud: five of the seven places the
 * character appears draw it at 32-44px. Strands, folds and highlights are
 * switched off there, and a simpler eye that still shows its colour is used.
 */
export const SMALL_BELOW = 64;

/**
 * Where a hat's brim sits on each face — generated by `hatLine()` in the art
 * geometry. A hat that covers the head hides the hair above this line, so
 * it never floats on top of a big head of hair. A test keeps these numbers
 * equal to the generator's.
 */
export const HAT_LINE: { [shape in FaceShape]: number } = {
  round: 37.5,
  oval: 35.5,
  square: 38.5,
  heart: 35.5
};

/** Hats worn over the head. A crown is worn IN the hair, so it hides nothing. */
export const HATS_OVER_HAIR = ['cap', 'beanie', 'wizard', 'bobble-hat'];

/** Styles with a part that hangs behind the head. */
export const HAIR_WITH_BACK: HairStyle[] = ['long', 'curly', 'bun', 'afro', 'coils', 'braids', 'locs'];

/**
 * Texture as a rim drawn just inside the hair's edge — the design the roadmap
 * explains: it composes with every style instead of needing a silhouette per
 * style per texture. Smooth draws no rim at all.
 */
export const TEXTURE: { [texture: string]: { width: number; dash: string } } = {
  smooth: { width: 0, dash: 'none' },
  wavy: { width: 2.4, dash: '7 5' },
  coily: { width: 3.6, dash: '.5 3.6' }
};

/**
 * A darker tone of a colour, for the side facing away from the light. Mixed
 * toward the theme's deep violet rather than black: a shadow that leans
 * violet belongs to the particle field; a grey one looks like dirt.
 */
export function shade(colour: string, amount = 0.3): string {
  const hex = /^#([0-9a-f]{6})$/i.exec(colour || '');
  if (!hex) {
    return colour;
  }
  const from = parseInt(hex[1], 16);
  const to = 0x2a1640;
  const channel = (value: number, shift: number) => (value >> shift) & 255;
  return '#' + [16, 8, 0].map(shift => {
    const a = channel(from, shift);
    const b = channel(to, shift);
    return Math.round(a + (b - a) * amount).toString(16).padStart(2, '0');
  }).join('');
}

export interface AvatarLayers {
  back?: string;
  body?: string;
  ears: string;
  face: string;
  brows: string;
  eyes: string;
  mouth: string;
  hair: string;
  glasses?: string;
  hat?: string;
  /** True when a hat covers the head, so the hair above its brim is hidden. */
  coversHair: boolean;
  hatLine: number;
}

const FACES: FaceShape[] = ['round', 'oval', 'square', 'heart'];

/** The parts to draw, back to front. */
export function avatarLayers(avatar: Avatar, framing: 'portrait' | 'full'): AvatarLayers {
  const face = FACES.includes(avatar.faceShape) ? avatar.faceShape : 'round';
  const hat = worn('hat', avatar.hat);
  const glasses = worn('glasses', avatar.glasses);
  const top = worn('top', avatar.top) || 'none';
  return {
    back: HAIR_WITH_BACK.includes(avatar.hairStyle) ? `hair-back-${avatar.hairStyle}-${face}` : undefined,
    body: framing === 'full' ? `body-${top}` : undefined,
    ears: `ears-${face}`,
    face: `face-${face}`,
    brows: 'brows',
    eyes: `eyes-${avatar.eyeShape || 'round'}`,
    mouth: `mouth-${avatar.mouthShape || 'smile'}`,
    hair: `hair-${avatar.hairStyle || 'short'}-${face}`,
    glasses: glasses ? `glasses-${glasses}-${face}` : undefined,
    hat: hat ? `hat-${hat}-${face}` : undefined,
    coversHair: !!hat && HATS_OVER_HAIR.includes(hat),
    hatLine: HAT_LINE[face]
  };
}

/**
 * The colours, as CSS custom properties on the character's <svg>. The sprite
 * names each one explicitly, since CSS is not guaranteed to inherit into the
 * content a <use> clones unless asked for (MDN, on <use>).
 */
export function avatarVars(avatar: Avatar, size: number): string {
  const small = size < SMALL_BELOW;
  const texture = TEXTURE[avatar.hairTexture] || TEXTURE.smooth;
  return [
    `--skin:${avatar.skin}`,
    `--skin-shade:${shade(avatar.skin, 0.22)}`,
    `--hair:${avatar.hairColour}`,
    `--hair-shade:${shade(avatar.hairColour, 0.38)}`,
    `--hair-light:${lighten(avatar.hairColour, 0.32)}`,
    `--eye:${avatar.eyeColour}`,
    `--tex-w:${texture.width}`,
    `--tex-dash:${texture.dash}`,
    `--detail:${small ? 'none' : 'inline'}`,
    `--small:${small ? 'inline' : 'none'}`,
    // A heavier line keeps the silhouette crisp when the whole face is 30px wide
    `--line-w:${small ? 2.1 : 1.25}`
  ].join(';');
}

function worn(slot: 'hat' | 'glasses' | 'top', id: string): string | undefined {
  const item = findItem(slot, id);
  return item && item.id !== NO_ITEM ? item.id : undefined;
}
